language: python
sudo: false
cache: pip

python: 
        - "3.6"

addons:
    postgresql: "12.0"
    apt:
        packages:
            - expect-dev
            - python-lxml
            - python-simplejson
            - python-serial
            - python-yaml
            - postgresql-12
            - postgresql-client-12

env:
    global:
    - VERSION="13.0" TESTS="0" LINT_CHECK="0"

    matrix:
    - LINT_CHECK="1"
    - TESTS="1" ODOO_REPO="odoo/odoo"

services:
    - postgresql

before_script:
  - psql -c 'create database template1;' -U postgres

before_script:
  - cp config/database.yml.travis config/database.yml

install:
    - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
    - travis_install_nightly

script:
    - travis_run_tests

after_success:
    - travis_after_tests_success
